language: python
python:
  - "3.6"
install:
  - pip install -r requirements-dev.txt
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - python -m pytest
  - python -m flake8
after_script:
  - coveralls
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT