version: "3"
services:
  web:
    container_name: banking-web
    environment:
       - LC_ALL=C.UTF-8
       - LANG=C.UTF-8
    env_file: .env
    build: .
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - .:/code
    command: /bin/bash -c "FLASK_APP=run.py FLASK_DEBUG=1 python -m flask run --port 3000 --host 0.0.0.0"
  db:
    container_name: banking-db
    image: postgres:10.0
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=banking_db
  redis:
    container_name: banking-redis
    image: redis:latest
    ports:
      - 6379:6379
  # queue:
  #   container_name: banking-queue
  #   image: rabbitmq:3-management
  #   expose:
  #     - 5672
  #   hostname: banking-queue
  #   ports:
  #     - "8080:15672"
  #     - "5672:5672"
  #   network_mode: "bridge"
  #   environment:
  #     - RABBITMQ_ERLANG_COOKIE=secret
  #     - RABBITMQ_DEFAULT_USER=root
  #     - RABBITMQ_DEFAULT_PASS=root
