"""empty message

Revision ID: 373bff7e93ec
Revises: 
Create Date: 2017-10-24 12:09:26.716264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '373bff7e93ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(length=80), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    # ### end Alembic commands ###
