"""empty message

Revision ID: 52b7d62d1933
Revises: b1ebc39e56b0
Create Date: 2017-11-05 19:48:55.302615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52b7d62d1933'
down_revision = 'b1ebc39e56b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriber_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('event_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_type.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscriber.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('subscriber_event_type_id_fkey', 'subscriber', type_='foreignkey')
    op.drop_column('subscriber', 'event_type_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriber', sa.Column('event_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('subscriber_event_type_id_fkey', 'subscriber', 'event_type', ['event_type_id'], ['id'])
    op.drop_table('subscriber_event')
    # ### end Alembic commands ###
