"""empty message

Revision ID: 736b8ca91ac6
Revises: 86707faf9173
Create Date: 2017-10-29 19:05:03.143673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '736b8ca91ac6'
down_revision = '86707faf9173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_event_type_entity', table_name='event_type')
    op.create_index(op.f('ix_event_type_entity'), 'event_type', ['entity'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_type_entity'), table_name='event_type')
    op.create_index('ix_event_type_entity', 'event_type', ['entity'], unique=True)
    # ### end Alembic commands ###
