"""empty message

Revision ID: b1ebc39e56b0
Revises:
Create Date: 2017-11-03 00:59:12.397385

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = 'b1ebc39e56b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=True),
    sa.Column('password', sqlalchemy_utils.types.password.PasswordType(
        schemes=[
            "pbkdf2_sha512",
            "md5_crypt"
        ],
        deprecated=["md5_crypt"]
    ), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('initial_balance', sqlalchemy_utils.types.currency.CurrencyType(length=3), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_number'), 'account', ['number'], unique=True)
    op.create_index(op.f('ix_account_password'), 'account', ['password'], unique=False)
    op.create_table('event_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('entity', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_type_entity'), 'event_type', ['entity'], unique=False)
    op.create_index(op.f('ix_event_type_name'), 'event_type', ['name'], unique=True)
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parameters', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('event_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_version'), 'event', ['version'], unique=False)
    op.create_table('subscriber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=False),
    sa.Column('event_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriber_email'), 'subscriber', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriber_email'), table_name='subscriber')
    op.drop_table('subscriber')
    op.drop_index(op.f('ix_event_version'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_event_type_name'), table_name='event_type')
    op.drop_index(op.f('ix_event_type_entity'), table_name='event_type')
    op.drop_table('event_type')
    op.drop_index(op.f('ix_account_password'), table_name='account')
    op.drop_index(op.f('ix_account_number'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
